name: eufaloportugues
description: This app helps you to increase your portuguese vocabulary.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
